OrderBundle\Entity\Cart:

    type: entity
    table: null
    repositoryClass: OrderBundle\Repository\CartRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        number:
            type: string
            length: '16'
        date:
            type: datetime
        status:
            type: string
            length: '16'
    oneToMany:
## lines represente la propriétée privée $lines de la classe Cart  ##
        lines:
## on indique l'entitée ciblée
            targetEntity: OrderBundle\Entity\Line
## avec mappedBy on indique a Cart qu'il est mappé par Cart present dans l'entitée Line  ## 
            mappedBy: cart
            cascade: ['persist', 'remove']
    manyToOne:
        customer:
            targetEntity: OrderBundle\Entity\Customer
    lifecycleCallbacks: {  }
